AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'

# Rails:
#  Enabled: true

Layout/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 15 lines of code.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#short-methods'
  Max: 15
  Enabled: true

Metrics/AbcSize:
  Max: 18
  Enabled: true

# Rails 5 only: https://github.com/bbatsov/rubocop/issues/3629
# Rails/HttpPositionalArguments:
#  Enabled: false

# Rails/ApplicationRecord:
#  Enabled: false

# Ruby 2.4 only
Lint/UnifiedInteger:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
