wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/june-2017.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/may-2017.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/april-2017.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/march-2017.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/february-2017.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/january-2017.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/december-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/november-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/october-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/September-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/August-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/July-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/June-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/May-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/April-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/March-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/February-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/January-2016.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/December-2015.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/November-2015.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/October-2015.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/September-2015.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/August-2015.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/July-2015.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/June-2015.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/May-2015.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/April-2015.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/March-2015.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2015-February.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2015-January.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2014.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2013.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2012.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2011.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2010.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2009.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2007-2008.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2005-2006.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2003-2004.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/2000-2002.zip
wget --no-clobber http://www.asxhistoricaldata.com/wp-content/uploads/1997-1999.zip
